# Generated by Django 4.2.7 on 2023-11-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="category",
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name="Categories",
        ),
    ]
